//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
function loadData() {
    $.blockUI();
    $.ajax({
        url: appData.siteUrl + 'api/v1/alumnos/' + pageData.idAlumno,
		type: 'GET',
        success: function (data) {
            $.unblockUI();
			
			// Propiedades Escalares
            $('#lb-nombres').text(data.Nombres ? data.Nombres : '-');
            $('#lb-apellidos').text(data.Apellidos ? data.Apellidos : '-');
            $('#lb-fecha-nacimiento').text(data.FechaNacimiento ? Globalize.formatDateUsingMask(Globalize.parseDateISOString(data.FechaNacimiento)) : '-');
        },
        error: function(xhr) {
            $.unblockUI();
			if (xhr.status !== 500) {
				var result = $.parseJSON(xhr.responseText);
				showErrors(result.Errors, result.Warnings,
						   function() { appData.goBack(); });
			} else {
				showApplicationFatalErrorMessage();
			}
        }		
    });
}
