//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Configuration;
using System.Linq;
using Unir.Architecture.SuperTypes.DataAccessBase;
using Unir.Architecture.SuperTypes.DistributedServicesBase;
using Unir.ErpAcademico.DataAccessModules;
using Autofac;

namespace Unir.ErpAcademico.DistributedServices
{
    public class DddAppContainerBase : IocContainer
    {
	    public DddAppContainerBase(Action<ContainerBuilder> builderAction) : base(builderAction)
        {
        }
	
		protected override void ConfigureContainer(ContainerBuilder builder)
        {
            base.ConfigureContainer(builder);
			
            var connectionString = ConfigurationManager.ConnectionStrings["DDDBd"];
            if (connectionString == null)
                throw new ConfigurationErrorsException("Connection String Key: DDDBd");

            //-> Servicios de Aplicación
            builder.RegisterAssemblyTypes(typeof(Unir.ErpAcademico.ApplicationServices.Capacitacion.Services.IAlumnosAppServices).Assembly)
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope()
                .Where(t => t.Name.EndsWith("AppServices"))
                .PropertiesAutowired();
            builder.RegisterAssemblyTypes(typeof(Unir.ErpAcademico.ApplicationServices.Capacitacion.Services.IAlumnosAppServices).Assembly)
                .InstancePerLifetimeScope()
                .Where(t => t.Name.EndsWith("AppServices"))
                .PropertiesAutowired();

            //-> Servicios de Dominio
            builder.RegisterAssemblyTypes(typeof(Unir.ErpAcademico.DomainModules.Capacitacion.Services.IAlumnosService).Assembly)
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope()
                .Where(t => t.Name.EndsWith("Service"))
                .PropertiesAutowired();

            //-> Repositorios
            builder.RegisterAssemblyTypes(typeof(Unir.ErpAcademico.DomainModules.Capacitacion.Services.IAlumnosService).Assembly, 
										  typeof(Unir.ErpAcademico.DataAccessModules.Capacitacion.Repositories.AlumnosRepository).Assembly)
                .AsImplementedInterfaces()
                .InstancePerLifetimeScope()
                .Where(t => t.Name.EndsWith("Repository"))
                .PropertiesAutowired();

            //-> Unit of Work
            builder.RegisterType<MainUnitOfWork>().As<IQueryableUnitOfWork>()
                .InstancePerLifetimeScope()
                .WithParameter(new TypedParameter(typeof(string), connectionString.ConnectionString))
                .PropertiesAutowired();			
		}
	}
}
