//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
var pageData = {
};
$(document).ready(function () {
    loadAlumnoCreateComponents();
    loadAlumnoState();
    
    $('#btn-save').click(function() {
        var errors = new Array();

        var params = getAlumnoCreateParameters();
        validateAlumno(params, errors);

        if (errors.length === 0) {
            $.blockUI();
            $.ajax({
                url: appData.siteUrl + 'api/v1/alumnos',
                data: $.toJSON(params),
				type: 'POST',
                success: function (data, status, xhr) {
                    $.unblockUI();
					if (xhr.status === 201)
						popupContinueEditAlumno(data.Id);
					else
						appData.goBack();
                },
				error: function(xhr) {
				    $.unblockUI();
				    if (xhr.status !== 500) {
				        var result = $.parseJSON(xhr.responseText);
				        showErrors(result.Errors, result.Warnings,
								   function() { appData.goBack(); });
				    } else {
				        showApplicationFatalErrorMessage();
				    }			
				}
            });
		} else {
			showErrors(errors);
		}
    });
});

function popupContinueEditAlumno(id) {
    var buttons = new Object();
    buttons[Globalize.formatMessage('TextYes')] = function () {
        appData.redirectTo('Alumno/CreationEdit/' + id);
    };
    buttons[Globalize.formatMessage('TextNo')] = function () {
        $(this).dialog('close');
        appData.goBack();
    };
    showCustomMessage({
        message: Globalize.formatMessage('QuestionContinueEditing'),
        buttons: buttons,
        open: function () {
            popup = $(this);
        }
    });
}
