//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Collections.Generic;
using Unir.Architecture.SuperTypes.ApplicationServicesBase.AppServicesUtility;
using Unir.Architecture.SuperTypes.PresentationBase.ActionsParameters;
using Unir.Architecture.SuperTypes.PresentationBase.Models;
using Unir.Architecture.SuperTypes.PresentationBase.ResultData;
using Unir.ErpAcademico.ApplicationServices.Capacitacion.Dto.Alumnos;
using Unir.ErpAcademico.ApplicationServices.Capacitacion.Services;
using Unir.ErpAcademico.ApplicationServices.Capacitacion.Services.Specifications.Alumnos;
using Unir.ErpAcademico.WebCapacitaciones.Parameters.Capacitacion.Alumno;

namespace Unir.ErpAcademico.WebCapacitaciones.Models.Capacitacion
{
	public class AlumnoModelBase : ModelSuperType
    {
	}
}
