//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
function loadAlumnoData() {
    $.blockUI();
    $.ajax({
        url: appData.siteUrl + 'api/v1/alumnos/' + pageData.idAlumno,
		type: 'GET',
        success: function (data, status, xhr) {
            $.unblockUI();			
			pageData.displayNameAlumno = data.DisplayName;			
			
			// Propiedades Escalares
			$('#txt-nombres').val(data.Nombres);
			$('#txt-apellidos').val(data.Apellidos);
			$('#txt-fecha-nacimiento').datepicker('setDate',data.FechaNacimiento ? Globalize.formatDateUsingMask(Globalize.parseDateISOString(data.FechaNacimiento),'YYYY-MM-DD HH:mm:ss') : null);
			//$('#txt-fecha-nacimiento').datepicker("option", "dateFormat", 'yy-mm-dd HH:mm:ss');
			/*$('#txt-fecha-nacimiento').datepicker({
                dateFormat: 'yy-dd-mm',
                onSelect: function (datetext) {
                    var d = new Date(); // for now

                    var h = d.getHours();
                    h = (h < 10) ? ("0" + h) : h;

                    var m = d.getMinutes();
                    m = (m < 10) ? ("0" + m) : m;

                    var s = d.getSeconds();
                    s = (s < 10) ? ("0" + s) : s;

                    datetext = datetext + " " + h + ":" + m + ":" + s;

                    $('#datepicker').val(datetext);
                }
            });*/
			loadAlumnoState();
        },
        error: function(xhr) {
			$.unblockUI();
			if (xhr.status !== 500) {
				var result = $.parseJSON(xhr.responseText);
				showErrors(result.Errors, result.Warnings,
						   function() { appData.goBack(); });
			} else {
				showApplicationFatalErrorMessage();
			}	
        }		
    });
}
