//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Unir.Architecture.SuperTypes.DomainBase;
using Unir.Architecture.SuperTypes.DomainBase.ActionResult;
using Unir.Architecture.SuperTypes.DomainBase.Extensions;
using Unir.Architecture.SuperTypes.DataAccessBase;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Conventions;
using Unir.ErpAcademico.DataAccessModules.Capacitacion.Mapping.Alumnos;

namespace Unir.ErpAcademico.DataAccessModules
{
    public class MainUnitOfWorkBase
        : EfUnitOfWork
    {
        public MainUnitOfWorkBase(DbConnection connection)
            : base(connection) { }
        public MainUnitOfWorkBase(string connectionString)
            : base(connectionString) { HookUpOrphanDelete(); }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
			modelBuilder.Conventions.Remove<OneToManyCascadeDeleteConvention>();
			

			// -Alumnos- 
			modelBuilder.Configurations.Add(new AlumnoConfiguration());
        }
	}
}
