//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Web.Mvc;
using Unir.ErpAcademico.WebCapacitaciones.Parameters.Capacitacion.Alumno;
using Unir.Architecture.SuperTypes.PresentationBase.ActionsParameters;
using Unir.Architecture.SuperTypes.PresentationBase.Attributes;
using Unir.Architecture.SuperTypes.PresentationBase.Controllers;
using Unir.Architecture.SuperTypes.PresentationBase.Attributes.ParametersPersistence;
using Unir.Architecture.SuperTypes.PresentationBase.Resources;

namespace Unir.ErpAcademico.WebCapacitaciones.Controllers.Capacitacion
{
	public class AlumnoControllerBase : ControllerSuperType
	{
        #region Lectura de Datos
		
        /// <summary>
        /// Devuelve la Vista del Listado Principal de la entidad Alumno
        /// </summary>
        /// <returns>La Vista</returns>
        [HttpGet]
		[ModuleOperationAuthorize("Alumno: listar")]
        public virtual ActionResult List()
        {
            ViewBag.IsSelectionList = false;
            return View("~/Views/Capacitacion/Alumno/List.gen.cshtml");
        }
        /// <summary>
        /// Devuelve la Vista del Listado Principal de búsqueda y Selección de la entidad Alumno
        /// </summary>
        /// <returns>La Vista</returns>
        [HttpGet]
        [SearchNavigationList]
		[ModuleOperationAuthorize("Alumno: listar")]
        public virtual ActionResult SearchList()
        {
            ViewBag.IsSelectionList = true;
            return View("~/Views/Capacitacion/Alumno/List.gen.cshtml");
        }

        [HttpGet]
		[ModuleOperationAuthorize("Alumno: ver")]
        public virtual ActionResult Show(GetActionParameters parameters)
        {
            ViewBag.Id = parameters.Id;
            return View("~/Views/Capacitacion/Alumno/Show.gen.cshtml");
        }

        #endregion Lectura de Datos

        #region Persistencia

        [HttpGet]
		[ModuleOperationAuthorize("Alumno: crear")]
        public virtual ActionResult Create()
        {
            return View("~/Views/Capacitacion/Alumno/Create.gen.cshtml");
        }

        [HttpGet]
		[ModuleOperationAuthorize("Alumno: editar")]
        public virtual ActionResult Edit(GetActionParameters parameters)
        {
            ViewBag.Id = parameters.Id;
            return View("~/Views/Capacitacion/Alumno/Edit.gen.cshtml");
        }
		
        [HttpGet]
		[ModuleOperationAuthorize("Alumno: editar")]
        public virtual ActionResult CreationEdit(GetActionParameters parameters)
        {
            ViewBag.Id = parameters.Id;
            return View("~/Views/Capacitacion/Alumno/Edit.gen.cshtml");
        }

        #endregion Persistencia
	}
}
