//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Unir.Architecture.SuperTypes.DomainBase;
using Unir.Architecture.SuperTypes.DomainBase.ActionResult;
using Unir.Architecture.SuperTypes.DomainBase.Attributes;
using Unir.Architecture.SuperTypes.DomainBase.Extensions;

namespace Unir.ErpAcademico.DomainModules.Capacitacion.Aggregates.Alumnos
{
	/// <summary>
	/// Alumno
	/// </summary>
	public partial class Alumno : Entity<int>
	{
		// Propiedades Primitivas		
		/// <summary>
		/// Descripción de Nombres
		/// </summary>
		[Alias("Nombres")]
		[StringLength(100, 
                      ErrorMessageResourceType = typeof(DomainCommonStrings), 
                      ErrorMessageResourceName = "ErrorValidationStringLenght")]
		public string Nombres { get; set; }
		
		/// <summary>
		/// Descripción de Apellidos
		/// </summary>
		[Alias("Apellidos")]
		[StringLength(100, 
                      ErrorMessageResourceType = typeof(DomainCommonStrings), 
                      ErrorMessageResourceName = "ErrorValidationStringLenght")]
		public string Apellidos { get; set; }
		
		/// <summary>
		/// Descripción de FechaNacimiento
		/// </summary>
		[Alias("Fecha de Nacimiento")]
		public DateTime? FechaNacimiento { get; set; }
		
	}
}
