//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
var pageData = {
    tbAlumnos: null
};

$(document).ready(function() {
    // Zona de Filtros
    loadAlumnosFilterArea();

    // Zona de Acciones sobre conjuntos de Datos, y otras opciones.
    if (pageData.isSelectionList === true) {
        loadAlumnosSelectionButtons();
    } else {
        loadAlumnosDataSetOptions();
    }
	
    // Ajuste de accesos según privilegios
    if (!pageModulePrivileges.canCreate)
        $('#btn-new-alumno').hide();
    if (!pageModulePrivileges.canDelete)
        $('#btn-delete-alumnos').hide();
    if (!pageModulePrivileges.canClone)
        $('#btn-clone-alumnos').hide();

    // Grilla de Datos
    loadAlumnosDataGrid();
});
