//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
function btnPrintAlumnosClick() {
    $('<div><ul class="list-errors"><li class="item-warning">' + Globalize.formatMessage('TextFeatureNotAvailable') + '</li></ul></div>').dialog({
        title: Globalize.formatMessage('TextPrint'),
        modal: true,
        close: function (event, ui) {
            $('.list-errors', this).empty();
        }
    });
}
