//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using Unir.Architecture.SuperTypes.DomainBase;
using Unir.Architecture.SuperTypes.DomainBase.ActionResult;
using Unir.Architecture.SuperTypes.DomainBase.Extensions;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.ComponentModel.DataAnnotations.Schema;
using Unir.ErpAcademico.DomainModules.Capacitacion.Aggregates.Alumnos;

namespace Unir.ErpAcademico.DataAccessModules.Capacitacion.Mapping.Alumnos
{
    public class AlumnoConfigurationBase : EntityTypeConfiguration<Alumno>
    {
		public AlumnoConfigurationBase()
		{	
			Configure();
		}
		
		public virtual void Configure()
		{
			//Mapeo de Propiedades y Columnas
			this.Property(r => r.Id).HasColumnName("IdAlumno");

			//Propiedades Escalares Opcionales y Requeridas
			this.Property(r => r.Nombres).IsRequired();
			this.Property(r => r.Apellidos).IsRequired();
			this.Property(r => r.FechaNacimiento).IsOptional();

			//Llave primaria y Nombre de Tabla
			this.HasKey(ll => ll.Id);
			this.ToTable("dbo.Alumno");

			//Configuración de Llave Primaria Autonumérica.
			this.Property(ll => ll.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
		}
	}
}
