//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
function getAlumnoGridColumns() {
    return [
        {
            sTitle: '<input type="checkbox" id="chk-alumnos-all" />',
            sWidth: "30px",
            bSortable: false
        },
        {
            sTitle: Globalize.formatMessage('ColumnId'),
            bSortable: true,
            sWidth: "15px",
            bVisible: isNull(pageData.AlumnosMainListParams.HiddenColumns) ? true : $.inArray(0, pageData.AlumnosMainListParams.HiddenColumns) < 0
        },
        {
            sTitle: Globalize.formatMessage('ColumnFechaNacimiento'),
            bSortable: true,
            sWidth: "30px",
            bVisible: isNull(pageData.AlumnosMainListParams.HiddenColumns) ? true : $.inArray(3, pageData.AlumnosMainListParams.HiddenColumns) < 0
        },
        {
            sTitle: Globalize.formatMessage('ColumnNombres'),
            bSortable: true,
            sWidth: "30px",
            bVisible: isNull(pageData.AlumnosMainListParams.HiddenColumns) ? true : $.inArray(1, pageData.AlumnosMainListParams.HiddenColumns) < 0
        },
        {
            sTitle: Globalize.formatMessage('ColumnApellidos'),
            bSortable: true,
            sWidth: "30px",
            bVisible: isNull(pageData.AlumnosMainListParams.HiddenColumns) ? true : $.inArray(2, pageData.AlumnosMainListParams.HiddenColumns) < 0
        },

        //{
        //    sTitle: Globalize.formatMessage('ColumnAlerts'),
        //    sWidth: "60px",
        //    bSortable: true
        //}, 
        {
            sTitle: Globalize.formatMessage('ColumnActions'),
            sWidth: "60px",
            bSortable: false
        }
    ];
}
