//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
function getAlumnosTableParameters(paramsTabla) {
    var params = getAlumnosFilterParameters();

    params.PageIndex = (paramsTabla.iDisplayStart / paramsTabla.iDisplayLength) + 1;
    params.ItemsPerPage = paramsTabla.iDisplayLength;
    params.OrderColumnPosition = paramsTabla.iSortCol_0;
    params.OrderColumnName = decode(
        paramsTabla.iSortCol_0,
        [
          1, 'id',
		  3, 'nombres',
		  4, 'apellidos',
		  2, 'fecha-nacimiento'
	]);
    params.OrderDirection = paramsTabla.sSortDir_0;

    // Establecer el estado de visibilidad de las columnas
    params.HiddenColumns = [];
    $.each(pageData.tbAlumnos.dataTable().fnSettings().aoColumns, function (item, value) {
        if (!value.bVisible) {
            params.HiddenColumns.push(item);
        }
    });


    return params;
}
function getAlumnosFilterParameters() {
    var params = new Object();

    // Texto Abierto
    params.FilterNombres = $('#txt-nombres').val().trim();
    params.FilterApellidos = $('#txt-apellidos').val().trim();
    params.FilterNombresApellidos = $('#txt-nombresapellidos').val().trim();
    

    // Rangos date time
    params.FilterFechaNacimientoFrom = $('#txt-fecha-nacimiento-from').val().isEmpty()
    ? null : Globalize.formatDateToISOString($('#txt-fecha-nacimiento-from').datepicker('getDate'));
    params.FilterFechaNacimientoTo = $('#txt-fecha-nacimiento-to').val().isEmpty()
    ? null : Globalize.formatDateToISOString($('#txt-fecha-nacimiento-to').datepicker('getDate'));
    return params;
}
