//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Radarc (http://radarc.net) - Radarc version: 4.9.1.22813 Formula: UNIR.1.1 version: 1.1
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
//     If you want to extend or modify the code use the designated extension points / user escapes as described in the product documentation.
// </auto-generated>
//------------------------------------------------------------------------------
function createAlumnoGridRow(rowData) {
    var row = [];
    row.push('<input type="checkbox" />');

	row.push('<span title="' + rowData.Id + '">' + summary(rowData.Id.toString(), 20, '...') + '</span>');
	row.push('<span title="' + rowData.Nombres + '">' + summary(rowData.Nombres, 20, '...') + '</span>');
	row.push('<span title="' + rowData.Apellidos + '">' + summary(rowData.Apellidos, 20, '...') + '</span>');
    if (rowData.FechaNacimiento) {
		row.push(Globalize.formatDateUsingMask(Globalize.parseDateISOString(rowData.FechaNacimiento)));
    } else {
        row.push('');
    }
    row.push('<span class="btn-opciones">' + Globalize.formatMessage('TextOptions') + '</span>');

    return row;
}
